In [4]:
# Question 1
import numpy as np
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
print("Correct option is:(A)")
print(a+b)

Correct option is:(A)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [6]:
# Question 2
arr=np.arange(12).reshape(3,4)
print("Correct option is:(A)")
arr[1:3,1:3]

Correct option is:(A)


array([[ 5,  6],
       [ 9, 10]])

In [7]:
# Question 3
arr = np.array([-2, -1, 0, 1, 2])
arr[arr < 0] = 0
arr

array([0, 0, 0, 1, 2])

In [8]:
# Question 4
matrix=np.array([[1, np.nan, 3], [4, 5, np.nan]])
mean=np.nanmean(matrix, axis=1)
print(mean)

[2.  4.5]


In [10]:
# Question 5
data=np.array([10, 20, 30, 40])
idx=np.array([True, False, True, False])
print("Correct option is :(A)")
print(data[idx])

Correct option is :(A)
[10 30]


In [11]:
# Question 6
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data, index=[100, 101, 102])
print(df)

        Name  Age
100    Alice   25
101      Bob   30
102  Charlie   35


In [12]:
# Question 7
df = pd.DataFrame({'A': [1, 2, np.nan], 'B': [np.nan, 5, 6]})
mean_B=df['B'].mean()   # value5.5
df['B']=df['B'].replace(np.nan,mean_B)
print(df)

     A    B
0  1.0  5.5
1  2.0  5.0
2  NaN  6.0


In [14]:
# Question 8
df=pd.DataFrame({
    'Region':['North', 'South', 'North', 'South'],
    'Sales':[100, 200, 150, 250],
    'Profit':[20, 30, 25, 40]
})
grouped_df=df.groupby('Region').agg({
    'Sales': 'sum',
    'Profit': 'mean'
}).reset_index()
print(grouped_df)

  Region  Sales  Profit
0  North    250    22.5
1  South    450    35.0


In [19]:
# Question 8
df=pd.DataFrame({
    'Region': ['North', 'South', 'North', 'South'],
    'Sales': [100, 200, 150, 250],
    'Profit': [20, 30, 25, 40]
})
print("Orginal data:",df)
mean_profit=df['Profit'].mean()
sum=df['Sales'].sum()
print("Total sum of Sales:",sum)
print("Total mean of Profit:",mean_profit)

Orginal data:   Region  Sales  Profit
0  North    100      20
1  South    200      30
2  North    150      25
3  South    250      40
Total sum of Sales: 700
Total mean of Profit: 28.75


In [20]:
import pandas as pd

df = pd.DataFrame({
    'Region': ['North', 'South', 'North', 'South'],
    'Sales': [100, 200, 150, 250],
    'Profit': [20, 30, 25, 40]
})

# Filter rows for each region
north = df[df['Region'] == 'North']
south = df[df['Region'] == 'South']

# Manually compute aggregates
north_sales = north['Sales'].sum()
north_profit = north['Profit'].mean()

south_sales = south['Sales'].sum()
south_profit = south['Profit'].mean()

# Create new summary DataFrame
summary = pd.DataFrame({
    'Region': ['North', 'South'],
    'Sales': [north_sales, south_sales],
    'Profit': [north_profit, south_profit]
})

# Reset index (already clean here, but for consistency)
summary = summary.reset_index(drop=True)

print(summary)

  Region  Sales  Profit
0  North    250    22.5
1  South    450    35.0


In [15]:
# Question 9
orders=pd.DataFrame({'order_id': [1, 2],'cust_id': [101, 102]})
customers=pd.DataFrame({'cust_id': [101, 103],'name': ['Alice', 'Bob']})
Merge=orders.merge(customers, on='cust_id', how='left')
print(Merge)

   order_id  cust_id   name
0         1      101  Alice
1         2      102    NaN


In [17]:
# Question 10
df = pd.DataFrame({
    'Date': ['2023-01-05', '2023-01-15', '2023-02-10','2023-02-20'],
    'Value': [10, 20, 30,30]
})
df['Date']=pd.to_datetime(df['Date'])
print(df.resample('ME',on='Date').sum())
#print(df.resample('ME',on='Date').sum().reset_index())

            Value
Date             
2023-01-31     30
2023-02-28     60
