In [2]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])

In [4]:
a+b

array([ 6,  8, 10, 12])

In [5]:
2*a

array([2, 4, 6, 8])

In [6]:
2*b-c-a           #2b-c-a

array([0, 0, 0, 0])

In [9]:
# Exercise 9.1
B=np.array([-0.562,0.630,-0.453,-0.299,-0.006])
G=np.array([0.194,0.507,0.287,0.132,-0.281])
F=np.array([0.605,-0.678,-0.436,-0.019,-0.291])
P=np.array([-0.074,-0.855,-0.689,-0.057,-0.139])
A=B-G+F
A

array([-0.151, -0.555, -1.176, -0.45 , -0.016])

In [10]:
B=A-P
B

array([-0.077,  0.3  , -0.487, -0.393,  0.123])

In [12]:
# Vector Product
a=np.array([1,2])
b=np.array([[11],[12]])
a@b

array([35])

In [13]:
a*b

array([[11, 22],
       [12, 24]])

### np.linalg.norm()

np → NumPy (Python’s numerical library).

linalg → linear algebra module inside NumPy.

norm() → a function that calculates different types of vector norms (or matrix norms).

What is a norm?

A norm is just a number that measures the “size” or “length” of a vector.
Different types of norms measure size differently:

1. Euclidean norm (L2, default)
2. Manhattan norm (L1)
3. chessboard norm(L infinity)
#### In np.linalg.norm(), the parameter ord means “order of the norm”.It tells NumPy which type of norm you want to compute.

In [14]:
import numpy as np

v = np.array([3, 4])

print(np.linalg.norm(v))             # Euclidean norm (sqrt(3^2 + 4^2) = 5)
print(np.linalg.norm(v, ord=1))      # Manhattan norm (3+4=7)       ord=1 → maximum column sum 
print(np.linalg.norm(v, ord=np.inf)) # Chessboard norm (max(3,4)=4) ord=np.inf → maximum row sum

5.0
7.0
4.0


In [16]:
# Exercise:9.2
v1=np.array([1,1])
v2=np.array([1,2,2])
v3=np.array([3,2,0,2,0,2,0,2])
v4=np.array([1,1])
v5=np.array([2,1])

In [20]:
euclidean_v1=np.sqrt(np.sum(v1**2))               
euclidean_v2=np.sqrt(np.sum(v2**2))                     
euclidean_v3=np.sqrt(v3 @ v3)       # square each number and sum them=21 here root 25 we will get 5.0 is the answer. 
manhattan_v1 = np.sum((v1))         #|1|+|1| =2
chessboard_v4 = np.max((v4))        #|2|,|1|= maximum value

In [21]:
print(euclidean_v1)
print(euclidean_v2)
print(euclidean_v3)
print(manhattan_v1)
print(chessboard_v4)

1.4142135623730951
3.0
5.0
2
1


In [22]:
euclidean_v1_linalg = np.linalg.norm(v1)
euclidean_v2_linalg = np.linalg.norm(v2)
euclidean_v3_linalg = np.linalg.norm(v3)

manhattan_v1_linalg = np.linalg.norm(v1, ord=1)

chessboard_v4_linalg = np.linalg.norm(v4, ord=np.inf)

print("\nWith np.linalg.norm:")
print("Euclidean (1,1):", euclidean_v1_linalg)
print("Euclidean (1,2,2):", euclidean_v2_linalg)
print("Euclidean (3,2,0,2,0,2,0,2):", euclidean_v3_linalg)
print("Manhattan (1,1):", manhattan_v1_linalg)
print("Chessboard (2,1):", chessboard_v4_linalg)


With np.linalg.norm:
Euclidean (1,1): 1.4142135623730951
Euclidean (1,2,2): 3.0
Euclidean (3,2,0,2,0,2,0,2): 5.0
Manhattan (1,1): 2.0
Chessboard (2,1): 1.0


In [25]:
# Exercise 9.3
import numpy as np

# Vectors
v1 = np.array([1, 1])
v2 = np.array([1, 2, 2])
v3 = np.array([3, 2, 0, 2, 0, 2, 0, 2])
v4 = np.array([2, 1])

# ---- Normalization using Euclidean norm (L2) ----
euclidean_v1 = v1 / np.linalg.norm(v1)
euclidean_v2 = v2 / np.linalg.norm(v2)
euclidean_v3 = v3 / np.linalg.norm(v3)

# ---- Normalization using Manhattan norm (L1) ----
manhattan_v1 = v1 / np.linalg.norm(v1, ord=1)

# ---- Normalization using Chessboard norm (L∞) ----
chessboard_v4 = v4 / np.linalg.norm(v4, ord=np.inf)

# ---- Print results ----
print("Normalized vectors:")
print("Euclidean (1,1):", euclidean_v1)
print("Euclidean (1,2,2):", euclidean_v2)
print("Euclidean (3,2,0,2,0,2,0,2):", euclidean_v3)
print("Manhattan (1,1):", manhattan_v1)
print("Chessboard (2,1):", chessboard_v4)

Normalized vectors:
Euclidean (1,1): [0.70710678 0.70710678]
Euclidean (1,2,2): [0.33333333 0.66666667 0.66666667]
Euclidean (3,2,0,2,0,2,0,2): [0.6 0.4 0.  0.4 0.  0.4 0.  0.4]
Manhattan (1,1): [0.5 0.5]
Chessboard (2,1): [1.  0.5]


#### 2-D Arrays as Matrices

In [27]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [28]:
A*10

array([[10, 20],
       [30, 40]])

In [31]:
# np.eye creates a unit matrix with given size as
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# np.diag either creates a diagonal matrix of a given vector, or if given a matrix, returns its diagonal
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
A=np.arange(12).reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np.diag(A)

array([ 0,  5, 10])

In [38]:
A=np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [39]:
A.T

array([[0, 2],
       [1, 3]])

In [40]:
B=A.reshape((1,4))
B

array([[0, 1, 2, 3]])

In [41]:
B.T

array([[0],
       [1],
       [2],
       [3]])

#### Numpy matrices

In [43]:
m=np.matrix("1 2;3 4")
m

matrix([[1, 2],
        [3, 4]])

In [45]:
#[[1,2],*[1,2],     # top-left:1*1+2*3=7
#[3,4]]   [3,4]     # top-right:1*2+2*4=10
                    # bottom-left:3*1+4*3=15
                    # bottom-right:3*2+4*4=22

In [44]:
m*m       

matrix([[ 7, 10],
        [15, 22]])

In [46]:
np.array(m) 

array([[1, 2],
       [3, 4]])

#### Matrix operations

In [48]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[11, 12], [13, 14]])
A - B

array([[-10, -10],
       [-10, -10]])

In [49]:
A*B

array([[11, 24],
       [39, 56]])

In [50]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [51]:
v = np.array([2, 3])
A/v

array([[0.5       , 0.66666667],
       [1.5       , 1.33333333]])

In [52]:
v = np.array([[2], [3]])
v

array([[2],
       [3]])

In [53]:
A/v

array([[0.5       , 1.        ],
       [1.        , 1.33333333]])

#### Matrix product

In [54]:
A = np.array([[1, 2, 3], [3, 4, 5]])
A

array([[1, 2, 3],
       [3, 4, 5]])

In [55]:
B = np.array([[-1], [0], [-2]])
B

array([[-1],
       [ 0],
       [-2]])

In [56]:
A @ B

array([[ -7],
       [-13]])