In [1]:
print("Hello World")

Hello World


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print("a:\n",a)
a.shape

a:
 [1 2 3 4 5 6]


(6,)

In [10]:
b=np.array([[1,2],[3,4]])
print("b:\n",b)
b.shape

b:
 [[1 2]
 [3 4]]


(2, 2)

In [9]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
b.reshape((4,))

array([1, 2, 3, 4])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
onecol=np.ones((4,))
zerocol=np.zeros((4,3))
np.column_stack((onecol,zerocol))

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [40]:
#Excercise 3.1 
onerow = np.ones((1, 4))         
zerosrow = np.zeros((1, 4))      
tworow = 2 * np.ones((1, 4))     

result = np.vstack(( -1 * onerow, zerosrow, tworow ))

print(result)

[[-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 2.  2.  2.  2.]]


In [103]:
a=np.arange(12).reshape((3,4))
print(a)
print(100+a,"\n")
print(2**+a,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]] 

[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]] 



In [52]:
#Exercise 3.2
b=np.arange(20).reshape((4,5))
print(2+2*b)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [106]:
a>6

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [55]:
 a==7

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [56]:
(a<3) | (a>8)

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [57]:
(a>4)&(a<7)

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [58]:
~(a>6)

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [63]:
a=np.arange(12)
print(a[::2])       #even numbers
print(a[5:11])      #reversing the numbers

[ 0  2  4  6  8 10]
[ 5  6  7  8  9 10]


In [65]:
a[5:11]=-1
a

array([ 0,  1,  2,  3,  4, -1, -1, -1, -1, -1, -1, 11])

In [67]:
a[[4,5,7,8]]

array([ 4, -1, -1, -1])

In [70]:
c=np.arange(12).reshape((3,4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
c[1,2]

np.int64(6)

In [80]:
c[0,3]

np.int64(3)

In [81]:
c[1]

array([4, 5, 6, 7])

In [83]:
c[:,2]

array([ 2,  6, 10])

In [84]:
c[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
c[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [108]:
#Exercise 3.3
a=+10+np.arange(20).reshape(4,5)*2
print(a)
a[3]=1+np.arange(5)
a

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [ 1,  2,  3,  4,  5]])

In [116]:
a=np.array([1,2,7,4])
i=np.array([True,False,True,False])
a[i]

array([1, 7])

In [117]:
i=a>5
i

array([False, False,  True, False])

In [118]:
a[i]

array([7])

In [119]:
a[a>5]

array([7])

In [13]:
import numpy as np
names = np.array(["Cyrus", "Darius", "Xerxes", "Artaxerxes", "Cyrus", "Darius"])
res=np.array([14,15,16,17,18,19])
# res[names == "Darius"]
res[names == "Cyrus"]

array([14, 18])

In [20]:
names=np.array(["Cyrus","Darius","Xerses"])
res=np.array([[17,14],[12,15],[10,11]])
print(res)
print(res[names == "Xerses"])
res[names == "Darius",:]

[[17 14]
 [12 15]
 [10 11]]
[[10 11]]


array([[12, 15]])

In [2]:
import numpy as np
a=np.random.randn(2,3)
a

array([[-0.50377938,  2.00436426, -1.09671731],
       [ 0.00721161,  0.31774574, -0.32146175]])

In [3]:
a[a<0]=0
a

array([[0.        , 2.00436426, 0.        ],
       [0.00721161, 0.31774574, 0.        ]])

In [4]:
a[a>0]=np.array([1,2,3])
a

array([[0., 1., 0.],
       [2., 3., 0.]])

In [89]:
#Exercise 3.4
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
score = np.array([126, 115, 130, 141, 132])
print(score[score<130])
print(score[names == "Statira"])
score[names == "Roxana"]+=10
print("scores:",score)

[126 115]
[115 141]
scores: [136 115 140 141 142]


In [95]:
x=np.random.choice(6, size=5)
x

array([0, 0, 5, 2, 3], dtype=int32)

In [97]:
1+np.random.choice(6,size=(2,4))

array([[4, 5, 5, 5],
       [3, 1, 5, 5]], dtype=int32)

In [104]:
nucleotides=["A","B","C","D"]
dna=np.random.choice(nucleotides, 10)
print(dna)
"".join(dna)

['B' 'B' 'A' 'A' 'C' 'C' 'A' 'A' 'D' 'C']


'BBAACCAADC'

In [115]:
import numpy as np

arr = [1, 2, 3, 4, 5,2,4]
replacement = np.random.choice(arr, size=3, replace=True)

without_replacement = np.random.choice(arr, size=3, replace=False)
print(replacement)              #allowed to pick the same element more than once.
print(without_replacement)      #allowed to pick the element only once.

[4 5 5]
[4 2 3]


In [117]:
np.random.normal(1000,100,size=20)

array([1035.82550675, 1017.61910517,  865.92750331,  890.03354865,
       1080.61927815,  987.48682259, 1074.22419679,  987.49259363,
       1142.56664658, 1033.71366482,  964.4648933 ,  936.50921679,
       1077.195707  , 1108.59965716, 1093.2396158 , 1038.00449595,
        854.42952149,  990.28524282,  946.76908845,  832.4258657 ])

In [121]:
np.random.binomial(2, 0.5, size=(2,4))      #random.binomial(n, p, size

array([[0, 1, 1, 1],
       [1, 1, 1, 0]], dtype=int32)

In [126]:
2*np.random.binomial(1, 0.5, size=10)-1     

array([ 1,  1, -1, -1,  1, -1,  1, -1,  1, -1], dtype=int32)

In [129]:
np.random.uniform(10,11,size=(2,3))                                  #random.uniform(low, high, size)

array([[10.64830459, 10.57130663, 10.75732049],
       [10.55912136, 10.79633925, 10.91258656]])

In [133]:
np.random.seed(1)
np.random.uniform(size=5)  

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [134]:
np.random.uniform(size=5)

array([0.09233859, 0.18626021, 0.34556073, 0.39676747, 0.53881673])

In [140]:
a = np.arange(12).reshape((3,4))
print(a)
print(a.sum())
print(a.sum(axis=0))         # add rows, preserve columns
print(a.sum(axis=1))         # add columns, preserve rows

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [151]:
a = a.astype(float)  # as np.nan is float, need a float array
a[1,2] = np.nan
print(a)
np.sum(a)

[[ 0.  1.  2.  3.]
 [ 4.  5. nan  7.]
 [ 8.  9. 10. 11.]]


np.float64(nan)